// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Qb5bWcWachgttHk1Ty6sahMgIT306O0',
    appId: '1:931745201122:web:833542e16a2ae2cee5d7bb',
    messagingSenderId: '931745201122',
    projectId: 'ionic-ec0mmerce',
    authDomain: 'ionic-ec0mmerce.firebaseapp.com',
    storageBucket: 'ionic-ec0mmerce.appspot.com',
    measurementId: 'G-5EQ6DT19EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8U7Iq8vt3v2XVA_4kdFFqnOrfKGYizBM',
    appId: '1:931745201122:android:ac2db18e1ce9f75ce5d7bb',
    messagingSenderId: '931745201122',
    projectId: 'ionic-ec0mmerce',
    storageBucket: 'ionic-ec0mmerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcdUmLs9hMtiQAwi6gEGQABAIm3tz9RYE',
    appId: '1:931745201122:ios:2dc9cd143337a22ae5d7bb',
    messagingSenderId: '931745201122',
    projectId: 'ionic-ec0mmerce',
    storageBucket: 'ionic-ec0mmerce.appspot.com',
    iosClientId: '931745201122-k5mmurpmi5ev7fet73jta2c50vvitumc.apps.googleusercontent.com',
    iosBundleId: 'com.example.slackCards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcdUmLs9hMtiQAwi6gEGQABAIm3tz9RYE',
    appId: '1:931745201122:ios:2dc9cd143337a22ae5d7bb',
    messagingSenderId: '931745201122',
    projectId: 'ionic-ec0mmerce',
    storageBucket: 'ionic-ec0mmerce.appspot.com',
    iosClientId: '931745201122-k5mmurpmi5ev7fet73jta2c50vvitumc.apps.googleusercontent.com',
    iosBundleId: 'com.example.slackCards',
  );
}
