// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC76VInc7eLTJM3XmB-xN5keiRIaiFT-I',
    appId: '1:111118284603:web:90b3c56c17fb6f1019691e',
    messagingSenderId: '111118284603',
    projectId: 'food-app-be2c3',
    authDomain: 'food-app-be2c3.firebaseapp.com',
    storageBucket: 'food-app-be2c3.appspot.com',
    measurementId: 'G-80V0QCPYPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0yUa7A_cBo2yQVzjBWFYVOKATrQ7Y5iQ',
    appId: '1:111118284603:android:f03a91ecdc1534b719691e',
    messagingSenderId: '111118284603',
    projectId: 'food-app-be2c3',
    storageBucket: 'food-app-be2c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxO7OliNvR2rde4UFKoJR4rimuzddwtzA',
    appId: '1:111118284603:ios:47c1a4556e46dc9519691e',
    messagingSenderId: '111118284603',
    projectId: 'food-app-be2c3',
    storageBucket: 'food-app-be2c3.appspot.com',
    iosClientId: '111118284603-pb37ked3afmcu160f2s8ptve01ehv7n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.slackCards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxO7OliNvR2rde4UFKoJR4rimuzddwtzA',
    appId: '1:111118284603:ios:47c1a4556e46dc9519691e',
    messagingSenderId: '111118284603',
    projectId: 'food-app-be2c3',
    storageBucket: 'food-app-be2c3.appspot.com',
    iosClientId: '111118284603-pb37ked3afmcu160f2s8ptve01ehv7n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.slackCards',
  );
}
